### ISSUE TITLE
signs out after the first test

### ISSUE THREAD

**Issue by vasco3** [clerkinc/example-cypress-nextjs#2]
I have a `test.cy.js`
```js
context("context", () => {
  before(() => {
    cy.login();
    cy.visit("/");
  }); 
  beforeEach(() => {
    Cypress.Cookies.preserveOnce("__session", "__client_uat");
  });
  it("should #1", () => {
    // signed in and passes tests
  });

  it("should #2", () => {
    // fails because signed out
  });

  it("should #3", () => {
   // fails because signed out
  });
});
```
but after running the first `it()` it signs out and fails the next `it()`

any suggestions?

**Comment by anagstef** [comment]
Hello! We have updated our example repo with the latest versions of all packages and also updated the Custom Commands to work with our latest packages.
Unfortunately, in the latest versions of Cypress it's not easy to preserve the cookies between tests. You can use the `cy.clerkSignIn()` custom command from the `@clerk/testing` package in every `it` you want to be signed in.
