### ISSUE TITLE
Update to include authMiddleware 

### ISSUE THREAD

**Issue by knightjdr** [clerkinc/example-cypress-nextjs#4]
Can this example be updated to include middleware following the [getting started](https://clerk.com/docs/nextjs/get-started-with-nextjs) guide for nextjs?

```
import { authMiddleware } from "@clerk/nextjs";

export default authMiddleware();

export const config = {
  matcher: ["/((?!.*\\..*|_next).*)", "/", "/(api|trpc)(.*)"],
};
```

Upgrading @clerk/nextjs to 4.19.1, adding the above middleware, and running `npm run dev` results in
```
error - (middleware)/node_modules/@clerk/nextjs/dist/esm/server-helpers.client.js (2:0) @ <unknown>
error - authMiddleware() can only be used in a server environment.
```

**Comment by anagstef** [comment]
Hello! We have updated our example repo. The update includes the latest versions of all packages, Custom Commands from the `@clerk/testing` package, and Testing tokens.
The new example uses the latest `clerkMiddleware`. 

You can learn more here: https://clerk.com/docs/testing/cypress
